// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xubfmxtcefkzpfjytavd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1YmZteHRjZWZrenBmanl0YXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzYyNDUsImV4cCI6MjA1OTI1MjI0NX0.JZxbHmLyV-Jigu0uQEql0xItr_vSQrUaKDCpNTJBFDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);